version: '3.7'

services:
  ai_app:
    build: .
    working_dir: /src/app
    ports:
      - "7000:7000"
    container_name: ai_app
    volumes:
      - ./:/src/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py

volumes:
  ai_app:
